# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inner_ball <- function(P) {
    .Call(`_samplelim_inner_ball`, P)
}

sample_points <- function(P, n, random_walk = NULL) {
    .Call(`_samplelim_sample_points`, P, n, random_walk)
}

